-- Nakaoni's Neovim Configuration File

require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colors")
require("user.cmp")
require("user.telescope")
require("user.lualine")
require("user.lsp")
require("user.treesitter")
require("user.autopairs")
require("user.comments")
require("user.gitsigns")
require("user.nvim-tree")
require("user.bufferline")
require("user.indentline")
require("user.toggleterm")
